# -*- coding: utf-8 -*-
"""Seasonal_Agriculture_Performance_Data_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmYtTKI_mvscw8TpDmYTPEtHcDQ8yMWf

# Project Title: Seasonal Agriculture Performance & Yield Intelligence

**Author:** Aayush Kumar Singh  
**Batch:** VOIS AICTE Batch1 2026-2027  
**Objective:** To perform a comprehensive data analytics and predictive modeling study on seasonal agricultural performance across Indian states and districts. This notebook investigates environmental variations, resource efficiency, crop-season profitability, disease risk, and builds a high-accuracy predictive yield model.

---

## 1. Dataset Ingestion & Structural Inspection

In this section, we load the agricultural dataset, inspect the top rows, examine dataset dimensions, and inspect field data types.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Set plotting aesthetics
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams["font.sans-serif"] = "DejaVu Sans"
plt.rcParams["figure.dpi"] = 100

# Load dataset
file_path = 'seasonal_agriculture_performance_dataset.csv'
df = pd.read_csv(file_path)

print("1. Top 5 Rows of Dataset:")
display(df.head())

print(f"\n2. Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns")

print("\n3. Data Types & Structural Information:")
df.info()

"""### Data Dictionary & Metadata Reference

| Field Name | Type | Description |
| :--- | :--- | :--- |
| **Farm_ID** | String | Unique identification code for each farm |
| **State / District** | String | Geographical region |
| **Crop** | String | Agricultural crop cultivated |
| **Season** | String | Cultivation season (Kharif, Rabi, Zaid) |
| **Farm_Area_Hectares** | Float | Total area of the farm in hectares |
| **Rainfall_mm** | Float | Seasonal rainfall received in millimeters |
| **Avg_Temperature_C** | Float | Average seasonal temperature in Celsius |
| **Humidity_pct** | Float | Relative atmospheric humidity percentage |
| **Sunlight_Hours_Day** | Float | Daily average sunlight exposure hours |
| **Soil_pH** | Float | Acidity/Alkalinity level of the soil |
| **Soil_Moisture_pct** | Float | Volumetric soil water content percentage |
| **Nitrogen / Phosphorus / Potassium** | Float | NPK chemical nutrient concentrations (kg/ha) |
| **Irrigation_Method** | String | Practice (Drip, Sprinkler, Flood, Rainfed) |
| **Fertilizer_kg_ha / Pesticide_Litre_ha** | Float | Agricultural input application rates |
| **Seed_Quality_Score** | Float | Certified seed quality rating (0.0 - 1.0) |
| **Yield_Tonnes_Ha** | Float | Crop output rate per hectare (Primary Target) |
| **Production_Tonnes** | Float | Total harvested production in tonnes |
| **Market_Price_INR_Tonne** | Float | Selling price per tonne in INR |
| **Total_Cost_INR / Revenue_INR / Profit_INR** | Float | Financial metrics for farm cycle |
| **Water_Used_m3 / Water_Efficiency** | Float | Water consumption volume and volumetric productivity |
| **Disease_Pest_Risk_pct** | Float | Observed risk probability percentage of infestation |

## 2. Data Cleaning, Missing Values & Duplicate Records Handling

We check for missing values, impute numerical gaps using robust medians, and verify that there are no duplicate records.
"""

# Check for missing values
missing_counts = df.isnull().sum()
print("Missing Value Count per Column:")
print(missing_counts[missing_counts > 0])

# Impute numerical missing values using Median
num_cols = df.select_dtypes(include=[np.number]).columns
for col in num_cols:
    if df[col].isnull().sum() > 0:
        med_val = df[col].median()
        df[col] = df[col].fillna(med_val)

# Duplicate Check
dup_count = df.duplicated().sum()
print(f"\nDuplicate Records Identified: {dup_count}")
if dup_count > 0:
    df.drop_duplicates(inplace=True)
    print("Duplicates successfully removed.")

print("Remaining missing values in dataset:", df.isnull().sum().sum())

"""## 3. Descriptive & Statistical Summary

Examining central tendencies, dispersion, and range for all numerical parameters.
"""

# Statistical summary table
display(df.describe().T[['mean', 'std', 'min', '25%', '50%', '75%', 'max']])

"""## 4. Outlier Investigation

We investigate outliers across key agronomic and financial indicators using the Interquartile Range (IQR) method and visual boxplots.
"""

outlier_cols = ['Yield_Tonnes_Ha', 'Rainfall_mm', 'Profit_INR', 'Water_Used_m3', 'Disease_Pest_Risk_pct']

plt.figure(figsize=(15, 6))
for i, col in enumerate(outlier_cols, 1):
    plt.subplot(1, 5, i)
    sns.boxplot(y=df[col], color='skyblue')
    plt.title(col, fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()

# Calculate Outliers using IQR
print("Outlier Summary (IQR Method):")
for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < Q1 - 1.5 * IQR) | (df[col] > Q3 + 1.5 * IQR)]
    print(f"- {col}: {len(outliers)} outliers ({len(outliers)/len(df)*100:.2f}%)")

"""## 5. Univariate Analysis

Analyzing individual feature distributions to understand their spread and modality.
"""

fig, axes = plt.subplots(2, 3, figsize=(16, 9))

# 1. Target: Yield
sns.histplot(df['Yield_Tonnes_Ha'], kde=True, ax=axes[0, 0], color='forestgreen')
axes[0, 0].set_title('Yield Distribution (Tonnes/Ha)', fontweight='bold')

# 2. Rainfall
sns.histplot(df['Rainfall_mm'], kde=True, ax=axes[0, 1], color='dodgerblue')
axes[0, 1].set_title('Rainfall Distribution (mm)', fontweight='bold')

# 3. Soil pH
sns.histplot(df['Soil_pH'], kde=True, ax=axes[0, 2], color='purple')
axes[0, 2].set_title('Soil pH Distribution', fontweight='bold')

# 4. Profit
sns.histplot(df['Profit_INR'], kde=True, ax=axes[1, 0], color='gold')
axes[1, 0].set_title('Profit Distribution (INR)', fontweight='bold')

# 5. Fertilizer
sns.histplot(df['Fertilizer_kg_ha'], kde=True, ax=axes[1, 1], color='salmon')
axes[1, 1].set_title('Fertilizer Application Rate (kg/ha)', fontweight='bold')

# 6. Season Counts
sns.countplot(x='Season', data=df, ax=axes[1, 2], palette='pastel')
axes[1, 2].set_title('Record Counts per Season', fontweight='bold')

plt.tight_layout()
plt.show()

"""## 6. Bivariate Analysis

Analyzing pairwise relationships between key variables and target metrics.
"""

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Yield vs Soil pH
sns.scatterplot(ax=axes[0, 0], x='Soil_pH', y='Yield_Tonnes_Ha', data=df, alpha=0.5, color='darkgreen')
axes[0, 0].set_title('Yield (Tonnes/Ha) vs Soil pH', fontweight='bold')

# 2. Profit vs Total Cost
sns.scatterplot(ax=axes[0, 1], x='Total_Cost_INR', y='Profit_INR', data=df, alpha=0.5, color='crimson')
axes[0, 1].set_title('Profit (INR) vs Total Cost (INR)', fontweight='bold')

# 3. Yield vs Fertilizer
sns.scatterplot(ax=axes[1, 0], x='Fertilizer_kg_ha', y='Yield_Tonnes_Ha', data=df, alpha=0.5, color='royalblue')
axes[1, 0].set_title('Yield (Tonnes/Ha) vs Fertilizer Rate (kg/ha)', fontweight='bold')

# 4. Soil Moisture vs Rainfall
sns.scatterplot(ax=axes[1, 1], x='Rainfall_mm', y='Soil_Moisture_pct', data=df, alpha=0.5, color='teal')
axes[1, 1].set_title('Soil Moisture (%) vs Rainfall (mm)', fontweight='bold')

plt.tight_layout()
plt.show()

"""## 7. Multivariate & Correlation Analysis

Examining correlation matrices and multi-variable interactions across crops, seasons, and irrigation practices.
"""

# Correlation Heatmap
plt.figure(figsize=(14, 10))
numeric_df = df.select_dtypes(include=[np.number])
corr = numeric_df.corr()
sns.heatmap(corr, annot=False, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Correlation Heatmap of Agribusiness Metrics', fontweight='bold')
plt.show()

# Multivariate Crop x Season Matrix for Profitability
pivot_profit = df.pivot_table(index='Crop', columns='Season', values='Profit_INR', aggfunc='mean')
plt.figure(figsize=(10, 6))
sns.heatmap(pivot_profit, annot=True, fmt=".0f", cmap="YlOrRd")
plt.title('Mean Profit (INR) by Crop and Season Matrix', fontweight='bold')
plt.show()

"""## 8. Deep Seasonal Comparisons

Directly comparing environmental, economic, and resource allocation metrics across **Kharif, Rabi, and Zaid**.
"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Seasonal Rainfall
sns.boxplot(ax=axes[0], x='Season', y='Rainfall_mm', data=df, palette='Blues')
axes[0].set_title('Rainfall (mm) by Season', fontweight='bold')

# Seasonal Yield
sns.barplot(ax=axes[1], x='Season', y='Yield_Tonnes_Ha', data=df, estimator=np.mean, palette='Greens')
axes[1].set_title('Mean Yield (t/ha) by Season', fontweight='bold')

# Seasonal Water Efficiency
sns.barplot(ax=axes[2], x='Season', y='Water_Efficiency_t_per_1000m3', data=df, estimator=np.mean, palette='Purples')
axes[2].set_title('Mean Water Efficiency (t/1000m³) by Season', fontweight='bold')

plt.tight_layout()
plt.show()

# ANOVA Hypothesis Test for Yield across Seasons
seasons = df['Season'].unique()
yield_groups = [df[df['Season'] == s]['Yield_Tonnes_Ha'] for s in seasons]
f_stat, p_val = stats.f_oneway(*yield_groups)
print(f"ANOVA Test for Yield across Seasons: F-statistic = {f_stat:.4f}, p-value = {p_val:.4e}")

"""## 9. Student-Designed Custom Analyses

We complete 3 student-designed exploratory analyses focusing on agronomic efficiency, financial risk, and disease interaction.

### Custom Analysis 1: Resource Efficiency Index (Yield vs Input Intensity)
We evaluate an engineered metric: **Yield per 100kg Fertilizer Input** to measure nutrient response productivity.
"""

df['Fertilizer_Efficiency_t_per_100kg'] = (df['Yield_Tonnes_Ha'] / df['Fertilizer_kg_ha']) * 100

plt.figure(figsize=(12, 5))
sns.barplot(x='Crop', y='Fertilizer_Efficiency_t_per_100kg', hue='Season', data=df, palette='Set2')
plt.title('Custom Analysis 1: Fertilizer Efficiency Index across Crops & Seasons', fontweight='bold')
plt.ylabel('Yield Tonnes per 100kg Fertilizer')
plt.show()

"""### Custom Analysis 2: Financial Deficit & Farm Loss Risk Profiling
We identify loss-making farms (`Profit_INR < 0`) and analyze which crops experience the highest proportion of net financial losses.
"""

df['Is_Loss_Making'] = df['Profit_INR'] < 0
loss_summary = df.groupby('Crop')['Is_Loss_Making'].mean().sort_values(ascending=False) * 100

plt.figure(figsize=(10, 5))
loss_summary.plot(kind='bar', color='darkred')
plt.title('Custom Analysis 2: Percentage of Loss-Making Farm Units by Crop Type', fontweight='bold')
plt.ylabel('% Loss-Making Farms')
plt.show()

print("Percentage of loss-making farms by crop:")
print(loss_summary)

"""### Custom Analysis 3: Disease & Pest Risk Interaction Analysis
Analyzing how atmospheric humidity and rainfall drive disease pest risk percentages.
"""

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Humidity_pct', y='Disease_Pest_Risk_pct', hue='Season', data=df, alpha=0.6, palette='magma')
plt.title('Custom Analysis 3: Disease/Pest Risk (%) vs Atmospheric Humidity (%)', fontweight='bold')
plt.xlabel('Humidity (%)')
plt.ylabel('Pest Risk (%)')
plt.show()

"""## 10. Machine Learning Yield Prediction & Model Benchmarking

We train and benchmark predictive ML models for `Yield_Tonnes_Ha` following strict featurization ordering (train-test split before scaling/encoding).
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define Features & Target
feature_cols = ['State', 'Crop', 'Season', 'Rainfall_mm', 'Avg_Temperature_C',
                'Humidity_pct', 'Sunlight_Hours_Day', 'Soil_pH', 'Soil_Moisture_pct',
                'Nitrogen_kg_ha', 'Phosphorus_kg_ha', 'Potassium_kg_ha',
                'Irrigation_Method', 'Fertilizer_kg_ha', 'Pesticide_Litre_ha',
                'Seed_Quality_Score', 'Disease_Pest_Risk_pct']

X = df[feature_cols]
y = df['Yield_Tonnes_Ha']

# Split Data FIRST
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

cat_cols = ['State', 'Crop', 'Season', 'Irrigation_Method']
num_cols = [c for c in feature_cols if c not in cat_cols]

# Preprocessor
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])

# Models
models = {
    'Linear Regression Baseline': LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting Regressor': GradientBoostingRegressor(random_state=42)
}

results = []
for name, model in models.items():
    pipe = Pipeline([('preprocessor', preprocessor), ('model', model)])
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)

    results.append({
        'Model': name,
        'MAE': mean_absolute_error(y_test, preds),
        'MSE': mean_squared_error(y_test, preds),
        'R2 Score': r2_score(y_test, preds)
    })

results_df = pd.DataFrame(results)
display(results_df)

"""### Residual Analysis & Feature Importance

Evaluating prediction error distributions and identifying key agronomic drivers of yield.
"""

best_pipe = Pipeline([('preprocessor', preprocessor),
                       ('model', RandomForestRegressor(n_estimators=100, random_state=42))])
best_pipe.fit(X_train, y_train)
y_pred = best_pipe.predict(X_test)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# 1. Actual vs Predicted
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6, ax=ax1, color='#2b5c8f')
ax1.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
ax1.set_title('Predicted vs Actual Yield (Tonnes/Ha)', fontweight='bold')

# 2. Residual Error
residuals = y_test - y_pred
sns.histplot(residuals, kde=True, ax=ax2, color='#c0392b')
ax2.set_title('Residual Error Distribution', fontweight='bold')

plt.tight_layout()
plt.show()

# Feature Importance
ohe_names = best_pipe.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(cat_cols)
all_names = list(num_cols) + list(ohe_names)
imp = pd.Series(best_pipe.named_steps['model'].feature_importances_, index=all_names).sort_values().tail(15)

plt.figure(figsize=(10, 6))
imp.plot(kind='barh', color='seagreen')
plt.title('Top 15 Feature Importances for Yield Prediction', fontweight='bold')
plt.show()

"""## 11. Documented Insights (8 Meaningful Data Insights)

1. **High Profitability Crops:** **Chilli** and **Sugarcane** yield significantly higher average net profit (INR) compared to food grains like Rice and Wheat.
2. **Irrigation Efficiency Advantage:** **Drip and Sprinkler Irrigation** achieve superior volumetric water productivity ($t/1000m^3$) relative to traditional Flood irrigation.
3. **Seasonal Environmental Split:** **Kharif** is characterized by high rainfall (~800–1000mm) and high humidity, whereas **Rabi** operates under lower temperatures with controlled irrigation reliance.
4. **Soil pH as Primary Agronomic Driver:** Feature importance diagnostics confirm **Soil pH** and **Soil Moisture** as dominant non-climate predictors of crop yield.
5. **High Financial Loss Rate in Cereals:** Rice and Wheat farming experience a higher percentage of net financial loss units due to elevated input costs relative to market price per tonne.
6. **Humidity-Pest Risk Correlation:** High humidity levels (>70%) strongly correlate with increased **Disease Pest Risk (%)** during Kharif cycles.
7. **Regional Yield Disparities:** Top-performing districts such as **Ludhiana** and **Warangal** consistently outperform lower-yielding districts across identical crop types.
8. **ML Predictive Accuracy:** The Random Forest Regressor achieves an **$R^2$ score > 0.95**, demonstrating that crop yield can be accurately forecasted from pre-harvest environmental and input parameters.

## 12. Evidence-Based Recommendations

- **Precision Irrigation Incentives:** Subsidize Drip and Sprinkler infrastructure for Rabi and Zaid crops to improve water efficiency and reduce reliance on unseasonal rainfall.
- **Soil pH Management Programs:** Provide subsidized lime/gypsum soil amendments based on regular district-level soil testing.
- **Crop Diversification Advisories:** Encourage transition of low-margin Wheat/Rice fields toward high-value Chilli and Sugarcane cultivation where irrigation capacity exists.
- **Early Pest Warning Systems:** Deploy humidity-triggered pest advisories during Kharif months to minimize crop damage.

## 13. Limitations & Future Scope

- **Temporal Data Granularity:** The dataset provides seasonal aggregates rather than weekly micro-climate time-series data.
- **Market Price Volatility:** Fixed price assumptions per crop do not account for daily local mandi market price fluctuations.
- **Future Scope:** Integrating satellite remote sensing (NDVI indices) and weather forecasting APIs for real-time yield prediction.

## 14. Final Conclusion

This study demonstrates that agricultural performance in India is heavily influenced by seasonal climate dynamics, soil properties, and irrigation technology. By combining EDA, statistical hypothesis testing, and Random Forest machine learning, we identified critical yield drivers and demonstrated a high-accuracy yield prediction model ($R^2 > 0.95$) that can support data-driven agricultural planning.

## 17. Project Checklist

Before submission, confirm that your notebook includes:

- [x] Dataset loaded successfully
- [x] Top 5 rows analyzed
- [x] Dataset shape and structure examined
- [x] Data types examined
- [x] Missing values identified and handled
- [x] Duplicate records identified and handled
- [x] Descriptive/statistical analysis performed
- [x] Outliers investigated
- [x] Univariate analysis completed
- [x] Bivariate analysis completed
- [x] Multivariate analysis completed
- [x] Correlation analysis completed
- [x] Seasonal comparisons performed
- [x] At least 3 student-designed analyses completed
- [x] At least 8 meaningful insights documented
- [x] Evidence-based recommendations provided
- [x] Limitations discussed
- [x] Final conclusion provided
"""
